[WIP] Landing Page
CraftAcademy/rails_messaging_october_17_lions pull request #4
Opened 2017-11-29 18:39 UTC by aljoh

As a user
  In order to use the site properly
  I need links the point to the right pages on the landing page

2017-11-30 14:04 UTC, diraulo reviewed
Is this still WIP or Ready?
Create a chore for refactoring the redundant steps I pointed in my review and I'll help you clean them up

2017-11-30 14:04 UTC, diraulo commented on features/step_definitions/landing_page_steps.rb
> +Then("I should be on the landing page") do
These 3 steps are redundant and could be refactored into one...

2017-11-30 18:54 UTC, aljoh commented on features/step_definitions/landing_page_steps.rb
> +Then("I should be on the landing page") do
Fixed

2017-12-01 11:33 UTC, diraulo reviewed
See my comments below

2017-12-01 11:33 UTC, diraulo commented on features/step_definitions/landing_page_steps.rb
> +When("I am on the landing page") do
This test here reads more like an assertion. If the intention is to visit the page, something like
`Given I visit the landing page` sounds more appropriate. 

Being on the landing page means I would have an implementation that looks like
`expect(page.current_path).to eq some_path`

and not `visit some_path`

2017-12-01 11:33 UTC, diraulo commented on features/step_definitions/landing_page_steps.rb
> +  if path == 'landing'
This can be refactored further...

Consider maybe extracting the logic for getting the `page_path` based on a page name to a method. Then you have a single assertion line that calls on that method.

You can have this as a refactoring ticket if you prefer.

2017-12-01 11:33 UTC, diraulo commented on features/landing_page.feature
> +    Then I am on the "sign_in" page
Not a blocker here, but this step here would read better as `Then I should be on the "sign_in" page

2017-12-01 12:02 UTC, diraulo approved these changes
:shipit:

2017-12-01 12:02 UTC, diraulo requested changes
Will someone fix the failing tests here?

2017-12-01 12:12 UTC, merged